/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSummariesRouteImport } from './routes/app.summaries'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppProcessGuideRouteImport } from './routes/app.process-guide'
import { Route as AppNoticeReplyRouteImport } from './routes/app.notice-reply'
import { Route as AppHearingsRouteImport } from './routes/app.hearings'
import { Route as AppDraftingRouteImport } from './routes/app.drafting'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCasesRouteImport } from './routes/app.cases'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSummariesRoute = AppSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessGuideRoute = AppProcessGuideRouteImport.update({
  id: '/process-guide',
  path: '/process-guide',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticeReplyRoute = AppNoticeReplyRouteImport.update({
  id: '/notice-reply',
  path: '/notice-reply',
  getParentRoute: () => AppRoute,
} as any)
const AppHearingsRoute = AppHearingsRouteImport.update({
  id: '/hearings',
  path: '/hearings',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftingRoute = AppDraftingRouteImport.update({
  id: '/drafting',
  path: '/drafting',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cases': typeof AppCasesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/notice-reply': typeof AppNoticeReplyRoute
  '/app/process-guide': typeof AppProcessGuideRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cases': typeof AppCasesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/notice-reply': typeof AppNoticeReplyRoute
  '/app/process-guide': typeof AppProcessGuideRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cases': typeof AppCasesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/hearings': typeof AppHearingsRoute
  '/app/notice-reply': typeof AppNoticeReplyRoute
  '/app/process-guide': typeof AppProcessGuideRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/summaries': typeof AppSummariesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/app/cases'
    | '/app/documents'
    | '/app/drafting'
    | '/app/hearings'
    | '/app/notice-reply'
    | '/app/process-guide'
    | '/app/research'
    | '/app/settings'
    | '/app/subscription'
    | '/app/summaries'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/app/cases'
    | '/app/documents'
    | '/app/drafting'
    | '/app/hearings'
    | '/app/notice-reply'
    | '/app/process-guide'
    | '/app/research'
    | '/app/settings'
    | '/app/subscription'
    | '/app/summaries'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/sitemap.xml'
    | '/app/cases'
    | '/app/documents'
    | '/app/drafting'
    | '/app/hearings'
    | '/app/notice-reply'
    | '/app/process-guide'
    | '/app/research'
    | '/app/settings'
    | '/app/subscription'
    | '/app/summaries'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/summaries': {
      id: '/app/summaries'
      path: '/summaries'
      fullPath: '/app/summaries'
      preLoaderRoute: typeof AppSummariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/process-guide': {
      id: '/app/process-guide'
      path: '/process-guide'
      fullPath: '/app/process-guide'
      preLoaderRoute: typeof AppProcessGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notice-reply': {
      id: '/app/notice-reply'
      path: '/notice-reply'
      fullPath: '/app/notice-reply'
      preLoaderRoute: typeof AppNoticeReplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hearings': {
      id: '/app/hearings'
      path: '/hearings'
      fullPath: '/app/hearings'
      preLoaderRoute: typeof AppHearingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafting': {
      id: '/app/drafting'
      path: '/drafting'
      fullPath: '/app/drafting'
      preLoaderRoute: typeof AppDraftingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDraftingRoute: typeof AppDraftingRoute
  AppHearingsRoute: typeof AppHearingsRoute
  AppNoticeReplyRoute: typeof AppNoticeReplyRoute
  AppProcessGuideRoute: typeof AppProcessGuideRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSummariesRoute: typeof AppSummariesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDraftingRoute: AppDraftingRoute,
  AppHearingsRoute: AppHearingsRoute,
  AppNoticeReplyRoute: AppNoticeReplyRoute,
  AppProcessGuideRoute: AppProcessGuideRoute,
  AppResearchRoute: AppResearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSummariesRoute: AppSummariesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
